# These are supported funding model platforms
# This is a basic workflow to help you get started with Actions

name: ws-scan

on:
  push:
    branches: [ master ]
    paths:
      - 'package.json'

  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      - name: 'NPM Install'
        run: npm install --package-lock
        
      - name: WhiteSource Scan
        run: |
          curl -LJO https://github.com/whitesource/unified-agent-distribution/releases/latest/download/wss-unified-agent.jar
          export WS_APIKEY=${{ WSAPIKEY }}
          export WS_USERKEY=${{ WSUSERKEY }}
          export WS_WSS_URL="https://saas-eu.whitesourcesoftware.com/agent"
          
          java -jar wss-unified-agent.jar -product "$GITHUB_REPOSITORY" -project "$GITHUB_REF" 

